name: build-test

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-18.04,ubuntu-latest,windows-latest]
        lazarus-versions: [dist, 2.0.6, 1.6.4, 1.6.2, 1.4.4, 1.2]
    steps:
    - uses: actions/checkout@v2
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v2.2.0
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        include-packages: "Synapse 40.1"
    - name: Build the Main Application
      run: lazbuild "src/lazaruswithgithubactions.lpi"
    - name: Build the Unit Tests Application
      run: lazbuild "tests/testconsoleapplication.lpi"
    - name: Run the Unit Tests Application
      run: bin/testconsoleapplication "--all" "--format=plain"
